#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : fabric
Version  : 2.5.0
Release  : 10
URL      : https://files.pythonhosted.org/packages/f9/14/e81b9425d450de0f34d8c49b46133aa5554a7f4f1f1f2e7857e66dfa270b/fabric-2.5.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/f9/14/e81b9425d450de0f34d8c49b46133aa5554a7f4f1f1f2e7857e66dfa270b/fabric-2.5.0.tar.gz
Summary  : High level SSH command execution
Group    : Development/Tools
License  : BSD-3-Clause
Requires: fabric-bin = %{version}-%{release}
Requires: fabric-license = %{version}-%{release}
Requires: fabric-python = %{version}-%{release}
Requires: fabric-python3 = %{version}-%{release}
Requires: paramiko
Requires: python-mock
BuildRequires : buildreq-distutils3
BuildRequires : paramiko
BuildRequires : python-mock

%description
To find out what's new in this version of Fabric, please see `the changelog

%package bin
Summary: bin components for the fabric package.
Group: Binaries
Requires: fabric-license = %{version}-%{release}

%description bin
bin components for the fabric package.


%package license
Summary: license components for the fabric package.
Group: Default

%description license
license components for the fabric package.


%package python
Summary: python components for the fabric package.
Group: Default
Requires: fabric-python3 = %{version}-%{release}

%description python
python components for the fabric package.


%package python3
Summary: python3 components for the fabric package.
Group: Default
Requires: python3-core
Provides: pypi(fabric)
Requires: pypi(invoke)
Requires: pypi(paramiko)

%description python3
python3 components for the fabric package.


%prep
%setup -q -n fabric-2.5.0
cd %{_builddir}/fabric-2.5.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1588711783
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/fabric
cp %{_builddir}/fabric-2.5.0/LICENSE %{buildroot}/usr/share/package-licenses/fabric/02d05f8f2b39d869923eee4336c55cd702564010
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/fab

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/fabric/02d05f8f2b39d869923eee4336c55cd702564010

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
